# Generated by Django 4.2.4 on 2023-08-08 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_videotoken_used_alter_videotoken_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videotoken",
            name="used",
        ),
    ]
