# Generated by Django 4.2.4 on 2023-08-09 19:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_remove_videotoken_used"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videotoken",
            old_name="video",
            new_name="lesson",
        ),
    ]
